### ISSUE TITLE
Лишний оператор после выполнения оптимизаций TAC

### ISSUE THREAD

**Issue by NikMozd** [Taally/FIIT_6_compiler#109]
Код программы:
```
var a;
input(a);
if a > 0
    goto 1;
else
    input(a);
1: print(a);
```

Получается такое:
![image](https://user-images.githubusercontent.com/12860284/84667387-f27d3300-af2a-11ea-82a2-d2f5b188c81a.png)

Лишний оператор: `L1: goto 1`

**Comment by Ex1sTs** [comment]
Разве он лишний? так с оптимизировался ТАК, была метка на L1, но оптимизация "Переход к переходам" протянула метку 1 сразу в if, оптимизация по noop'ам удалила метку L2 и протянула "1" в goto L2. Я однажды задал вопрос по поводу "недостижимых меток с переходами". Но оказалось, что у нас просто нет оптимизаций, которые занимаются удалением такого кода.

**Comment by Molkree** [comment]
Так, надо подумать. @NikMozd не думает, что так должно быть, мне со стороны тоже так кажется. Придётся разобраться чуть глубже, может быть ты и прав.

**Comment by Molkree** [comment]
Из внутренней переписки с @Ex1sTs:

> ну если я правильно понял Михалковича, он так задумал, что мы сами напишем оптимизацию, удаляющий такой код =)
И оно не убирает именно в ситуации когда у нас "метка + переход", потому что оптимизации на удаления кода не отрабатывают переход ( есть предположение, что они отрабатывают только на присваивания и т.п.)

> ну я спрашивал у Михалковича именно про ситуацию когда у нас
```
goto 1;
1: goto 2;
2: goto 3;
3: a = 1;
```

> после оптимизации
```
goto 3;
1: goto 3;
2: goto 3;
3: a = 1;
```

> и вот эта часть
```
1: goto 3;
2: goto 3;
```

> недостижимая, я спросил у Михалковича, он сказал "Да действительно, задание на такую оптимизацию я не давал"

> разумеется при учете, что на метку 1 и 2 нет других переходов

**Comment by Molkree** [comment]
@Ex1sTs прав, сейчас всё так. Однако хочется, чтобы Удаление переходов к переходам за собой подчищало лишние инструкции.

**Comment by Ex1sTs** [comment]
@Molkree ну по сути своей, это уже похоже не на "подчистку лишних инструкций", а на удаление недостижимых ББл. И не очень охота прикручивать данный функционал к удалению переходов к переходам. Не будет ли лучше, тогда, реализовать "проверку" на достижимость ББл, через CFG. Предполагаю, если у ББл, нет родителей ( и это не первый ББл программы), то он недостижимый, и от него можно избавится. Однако это нужно обдумать и аргументировать.

**Comment by Molkree** [comment]
@Ex1sTs, это лишь один частный случай недостижимых бблоков, который специфичен для этой конкретной оптимизации.
Над удалением всех недостижимых бблоков мы думаем, да.
Отложим обсуждение этого, пофиксите сначала #124, пожалуйста.
