### ISSUE TITLE
ReplaceGotoToGoto превращает валидный код в недостижимый

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#124]
```
var a, b;
goto 1;
1: if (false)
    goto 2;
a = 6;
2: b = 5;
```
В результате первый переход превратится в `goto 2`, что неверно.
Вот [тут](https://github.com/Taally/FIIT_6_compiler/commit/2bfc60b190be1df6b483b9b6158639f2c66f6f64) я добавил тест на это.

**Comment by Molkree** [comment]
@Ex1sTs из внутренней переписки:

> у нас не может по идее быть такого случая в трехадресном коде

> он оптимизируется на этапе АСТ дерева

Пример, когда оптимизации на этапе AST-дерева не спасут:
```
var a, b, c;
input(a);
goto 1;
c = a < 0;
1: if (c)
    goto 2;
a = 6;
2: b = 5;
```

**Comment by Ex1sTs** [comment]
Подаю твой код в a.txt программы, на выходе получаю:
![image](https://user-images.githubusercontent.com/33717301/84899825-deb00900-b0b1-11ea-81cb-d9868ea42c2e.png)

выглядит все верно, или я не прав? goto 1 так и осталось меткой goto 1.

**Comment by Molkree** [comment]
Выключи `RemoveGotoThroughGoto`.

**Comment by NikMozd** [comment]
Зачем эта проверка? Все инструкции, подаваемые на вход оптимизации, и так непустые.
```commands[list[j].InstructionNum + 1] != null```
Что такое k?
Зачем это условие?
```CountGoTo(list, list[j].Label) <= 1```

**Comment by Ex1sTs** [comment]
@NikMozd 
3)CountGoTo(list, list[j].Label) <= 1 - это условия нужно для 3его случая в нашей задаче. Для него нужно учитывать, что в коде вида
1: if (усл) goto 2
существует только один единственный переход на метку 1, и только в этом случае делать оптимизацию. 
2) k - нужно тоже для случая 3, что бы добавить временную метку на ее соответствующее место, которая создается в случае реализации метода 3, это k зависит от того, сколько раз отрабатывает 3й случай.
1) Возможно это лишняя проверка, проверю сегодня после консультации, если что изменю

**Comment by NikMozd** [comment]
А если будет несколько переходов на метку 1, что тогда?

**Comment by Ex1sTs** [comment]
@NikMozd 
![image](https://user-images.githubusercontent.com/33717301/85052693-139b8900-b1a2-11ea-84ce-55891cd08bd4.png)
Исходя из теории. Если переходов будет несколько, в данном случае, оптимизация вида (3) не отработает.
