### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by NikMozd** [Taally/FIIT_6_compiler#133]
Список того, что необходимо отрефакторить в коде, ибо выглядит так себе:
- [x] обратные дуги и проверка приводимости (сделать экстеншеном графа или внести в граф)
- [ ] ~~сделать единый интерфейс для оптимизаций TAC, сделать их статическими~~
- [x] вынести в базовый класс тестов методы для построения CFG и т.п., чтобы уменьшить дублирование кода
- [ ] ~~сделать статическими классы алгоритмов - наследников GenericIterativeAlgorithm~~
- [x] исправить алгоритм для доступных выражений (AvailableExpressions), чтобы по минимуму переопределялся Execute и не использовались расширения List'а
- [x] заменить выражения вида `x is T && (x as T).Property`, используя pattern matching: `x is T t && t.Property`
- [x] сделать громоздкие условия в коде более компактными, особенно в оптимизациях по AST. Например, в OptExprSimilarNotEqual такое условие:
```
// Для цифр и значений bool :
binop.Left is IntNumNode && binop.Right is IntNumNode && (binop.Left as IntNumNode).Num == (binop.Right as IntNumNode).Num && (binop.Op == OpType.GREATER || binop.Op == OpType.LESS)
|| binop.Left is BoolValNode && binop.Right is BoolValNode && (binop.Left as BoolValNode).Val == (binop.Right as BoolValNode).Val && (binop.Op == OpType.GREATER || binop.Op == OpType.LESS)
|| binop.Left is IntNumNode && binop.Right is IntNumNode && (binop.Left as IntNumNode).Num == (binop.Right as IntNumNode).Num && binop.Op == OpType.NOTEQUAL
|| binop.Left is BoolValNode && binop.Right is BoolValNode && (binop.Left as BoolValNode).Val == (binop.Right as BoolValNode).Val && binop.Op == OpType.NOTEQUAL
// Для переменных :
|| binop.Left is IdNode && binop.Right is IdNode && (binop.Left as IdNode).Name == (binop.Right as IdNode).Name && (binop.Op == OpType.GREATER || binop.Op == OpType.LESS)
|| binop.Left is IdNode && binop.Right is IdNode && (binop.Left as IdNode).Name == (binop.Right as IdNode).Name && binop.Op == OpType.NOTEQUAL
```
- [x] в `GenericItertiveAlgorithmTests` переписать метод `AssertSet`, чтобы сравнение не зависело от порядка элементов

**ВАЖНО!!!** 
Не вливать какие-либо изменения по этому таску до одобрения @Molkree или @NikMozd

**Comment by Tessecrack** [comment]
Обратные рёбра, как расширение ControlFlowGraph сделаны. Проверю ещё раз и залью

**Comment by Tessecrack** [comment]
название файла оставить "BackEdges.cs"?

**Comment by Molkree** [comment]
> название файла оставить "BackEdges.cs"?

Дай ссылку на новый файл, скажу :)
Если там что-то кроме рёбер, то наверное нет.

**Comment by Tessecrack** [comment]
https://github.com/Tessecrack/FIIT_6_compiler/blob/master/LoopsInCFG/BackEdges.cs

**Comment by Tessecrack** [comment]
Или там прям рефакторинг-рефаткоринг нужен?)

**Comment by Molkree** [comment]
@Tessecrack, если ты сделал какие-то изменения и хочешь влить, то лучше заводи PR, так проще обсуждать и видеть сами изменения, чем на словах.

**Comment by Tessecrack** [comment]
@Molkree, с pr всё ок?

**Comment by Molkree** [comment]
Уже не важно, ты его влил! Будем фиксить потом значит.

**Comment by NikMozd** [comment]
@VadimKaryakin @VadimKaryakin а часики-то тикают. Если до конца дня не сделаете хотя бы три пункта, я этот таск у вас отберу

**Comment by Tessecrack** [comment]
Нашли выход с переопределением Execute в AvailableExpression

**Comment by TheTapog** [comment]
@NikMozd я делаю задание
> сделать единый интерфейс для оптимизаций TAC, сделать их статическими
не знаю как в c#8.0, но вроде в C7.3 статические классы не могут реализовывать интерфейсы

> сделать статическими классы алгоритмов - наследников GenericIterativeAlgorithm
с наследованием у статических классов тоже непонятно

**Comment by NikMozd** [comment]
По пункту
`сделать единый интерфейс для оптимизаций TAC, сделать их статическими`
дело скорее в том, что придётся делать классы визиторов статическими вплоть до Visitor, а абстрактность и статичность не сочетаются. Этот пункт закрываю

**Comment by NikMozd** [comment]
@Tessecrack и где ваши правки?

**Comment by Tessecrack** [comment]
Висят в pr вместе с доками

**Comment by NikMozd** [comment]
По пункту `сделать статическими классы алгоритмов - наследников GenericIterativeAlgorithm` согласен, тоже закрываю его

**Comment by Ex1sTs** [comment]
рефактор AssertSet и OptExprSimilarNotEqual в пуле #183

**Comment by Ukolnir** [comment]
рефактор (с возможностью кидать тапки) для оптимизаций:
- OptExprAlgebraic
- OptExprFoldUnary
- OptExprMultDivByOne
- OptExprTransformUnaryToValue
- OptExprWithOperationsBetweenConsts
висит в пуле #188

**Comment by TheTapog** [comment]
что получится если я залью свои рефактор для:
-> заменить выражения вида x is T && (x as T).Property, используя pattern matching: x is T t && t.Property
-> сделать громоздкие условия в коде более компактными, особенно в оптимизациях по AST
после @Ukolnir ?

**Comment by TheTapog** [comment]
короче, это задача нашей команды. сегодня залью 3 рефакторинга:
-> в GenericItertiveAlgorithmTests переписать метод AssertSet, чтобы сравнение не зависело от порядка элементов
-> заменить выражения вида x is T && (x as T).Property, используя pattern matching: x is T t && t.Property
-> сделать громоздкие условия в коде более компактными, особенно в оптимизациях по AST. 

а дальше сами решайте

**Comment by Ukolnir** [comment]
@TheTapog так я вроде ваши оптимизации не трогала. Так что конфликта не будет. Больше этого issue касаться не буду

**Comment by TheTapog** [comment]
#192 
-> заменить выражения вида x is T && (x as T).Property, используя pattern matching: x is T t && t.Property
-> сделать громоздкие условия в коде более компактными, особенно в оптимизациях по AST. 
-> вынести в базовый класс тестов методы для построения CFG и т.п., чтобы уменьшить дублирование кода

**Comment by Tessecrack** [comment]
pr с доками + AvailableExpressions висит, если силы есть - чекните

**Comment by Tessecrack** [comment]
`не использовались расширения List'а` тоже сделано

**Comment by NikMozd** [comment]
@Tessecrack а `RemoveExpression` и `ContainsExpression` - это что? обычными операциями типа `Remove` и `Contains` обойтись не удалось?

**Comment by Tessecrack** [comment]
@NikMozd  секунду

**Comment by Tessecrack** [comment]
@NikMozd полностью избавился от Remove и где можно от Contains (используется теперь в одном месте)

**Comment by NikMozd** [comment]
@Tessecrack пожалуйста, добавляй в комменты ссылки на свои правки, ибо искать их во всём проекте непросто

**Comment by Tessecrack** [comment]
Гит разве не отмечает изменения?

**Comment by NikMozd** [comment]
У нас 18 веток. В какой из них твои правки?

**Comment by Tessecrack** [comment]
@NikMozd  #181 в этом пуле лежат

**Comment by NikMozd** [comment]
@Tessecrack увидел, теперь ок

**Comment by TheTapog** [comment]
-> в GenericItertiveAlgorithmTests переписать метод AssertSet, чтобы сравнение не зависело от порядка элементов
вчера @Ex1sTs  переписал AsserSet в #183
