### ISSUE TITLE
Проверить содержимое документации

### ISSUE THREAD

**Issue by NikMozd** [Taally/FIIT_6_compiler#142]
Проверить полноту доков, исправить опечатки, обновить код (если он изменился/изменится с момента публикации дока), исправить отступы и форматирование.

**Comment by NikMozd** [comment]
+ проверить связи задач между собой (зависимые и предшествующие)

**Comment by NikMozd** [comment]
взял @tefadivan

**Comment by NikMozd** [comment]
Так как от @tefadivan ничего не слышно, таск переходит к @Taally @Ukolnir @ushakov-igor и @patceev

**Comment by Ukolnir** [comment]
Вот коммит с проверками по документации #216

**Comment by NikMozd** [comment]
дополнительные исправления в #222 и #223
