### ISSUE TITLE
AST: Оптимизация умножения на 0 (Рыженков, Евсеенко)

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#143]
Предполагаю, что забыли влить этот [файл](https://github.com/Taally/FIIT_6_compiler/blob/pirates/MultOptimizationVisitor.cs).

**Comment by Tessecrack** [comment]
В ASTOptimizer в List<Optimizations> добавь new OptExprMultZero(),

**Comment by Tessecrack** [comment]
![OptMultAndSum](https://user-images.githubusercontent.com/55711450/85100738-8c81fb80-b209-11ea-8233-48690fe124fd.png)
