### ISSUE TITLE
Некорректная работа OptExprAlgebraic

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#145]
Данная оптимизация обрабатывает все бинарные операции с числами, что приводит к ошибкам.
Пример:
```
var a;
a = 2 < 3;
```
превращается в:
```
var a;
a = 0;
```
@tefadivan

**Comment by NikMozd** [comment]
Предполагаю, что можно починить, добавив в `switch` пункт
```
default:
    return;
```

**Comment by NikMozd** [comment]
@tefadivan
