### ISSUE TITLE
AST: Оптимизация неравенства констант (Лутченко, Письменский)

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#146]
@d-enk, не вижу этого в общем репозитории.
![image](https://user-images.githubusercontent.com/12860284/85079826-6ee47000-b1d0-11ea-9346-969ba10c2a0a.png)

**Comment by d-enk** [comment]
Да, я пару дней назад тоже обнаружил эту проблему
Не мной писалась задача
Максим нашёл - допишет тесты забьёт
