### ISSUE TITLE
Исправить генерацию TAC для оператора if

### ISSUE THREAD

**Issue by NikMozd** [Taally/FIIT_6_compiler#147]
Сейчас данная программа
```
var a;
if a
    a = true;
```
преобразуется в TAC следующим образом:
```
if a goto L1
goto L2
L1: a = True
L2: noop
```
Исправить генерацию TAC таким образом, чтобы избавиться от лишнего `goto`, например, так:
```
#t1 = !a
if #t1 goto L1
a = True
L1: noop
```
Следует отметить, что такая оптимизация возможна лишь для краткой версии `if` (без ветки `else`).
Скорее всего придётся править много тестов.

**Comment by NikMozd** [comment]
Осталось проверить, что фикс правильный, и поправить тесты (24 штуки)

**Comment by NikMozd** [comment]
Взял @d-enk

**Comment by d-enk** [comment]
> Следует отметить, что такая оптимизация возможна лишь для краткой версии `if` (без ветки `else`).

чет не совсем понимаю, почему так нельзя
![image](https://user-images.githubusercontent.com/43112758/85201289-eb796a80-b306-11ea-9a35-f1e31375a2a6.png)

**Comment by NikMozd** [comment]
Думаю, что @Molkree имел в виду, что для if с двумя ветками выигрыша особого не будет

**Comment by d-enk** [comment]
Ну по крайней мере на привычных местах

**Comment by Ukolnir** [comment]
Вот уж здесь смысла я не вижу. В for мы исправили с трех блоков до двух ценой малых по сути усилий, а вот здесь... тоже уменьшение на один блок, но это не во всех случаях if, да и править дофига

**Comment by Molkree** [comment]
> да и править дофига

Обрати внимание, что 22 падающих теста это AST, которые не имеют к этому отношения.
То есть для исправления остаются "всего лишь" 23 теста.

**Comment by Ukolnir** [comment]
С for было тестов меньше :)

**Comment by Molkree** [comment]
@d-enk пишет:

> следующая ситуация
> преобразование ифов сделал
> с сохранением старой логики для ifelse
![image](https://user-images.githubusercontent.com/12860284/85207514-f5fd2980-b331-11ea-81b4-496f2f441f18.png)

> но при оптимизации в этом [месте](https://github.com/d-enk/FIIT_6_compiler/blob/master/TACOptimizations/ThreeAddressCodeGotoToGoto.cs#L120)
> возникает он теперь не находит метку с goto
так как теперь на нее ifgoto прыгает

> я с логикой этой оптимизации не знаком
просто добавлять ifgoto туда
выглядит крайне сомнительным
(выше проверка что должна быть четко одна метка еще, что такое условие может сломать вроде)

> в общем я хз как быть, кто писал эту оптимизацию?

> ну и эти пустые блоки выпиливаются после оптимизаций ну и до блоков дело не доходит
мб стоит забить?
![image](https://user-images.githubusercontent.com/12860284/85207551-32c92080-b332-11ea-944d-633be528aec4.png)

Это писали @Sirozu и @Ex1sTs

**Comment by d-enk** [comment]
https://github.com/d-enk/FIIT_6_compiler/tree/if-tac-change

**Comment by Molkree** [comment]
Ну я вижу, что оно падает. Это крик о помощи к @Sirozu @Ex1sTs или репорт бага?

**Comment by Ex1sTs** [comment]
Я к сожалению, не могу ни помочь, ни констатировать факт, что это баг, этот код был полностью переписан, и к сожалению не мной. Вероятнее раньше завтрашнего утра ответа не будет, извините.

**Comment by d-enk** [comment]
Ну я же написал

Хз насчёт бага, но чет мне кажется, что можно было написать так чтобы такое изменение не афектило

Насчёт крика о помощи
Ну блин нафиг тратить время на вникание, если можно спросить кто уже занимался этим

**Comment by Ex1sTs** [comment]
@d-enk 
[тут](https://github.com/Sirozu/FIIT_6_compiler/blob/master/TACOptimizations/ThreeAddressCodeGotoToGoto.cs)
исправленная версия, должно помочь в твоем случае, если что, мы добавим ее в мастер с ближайший пулом.

**Comment by d-enk** [comment]
@Ex1sTs
Там точно ifgoto не должен применяться?

Просто в обычном if там сразу на выход через ifgoto

Можешь в двух словах логику описать мне, пж

**Comment by Ex1sTs** [comment]
@d-enk 
там 3  случая для оптимизаций, 3й случай ( в котором у тебя выскакивала ошибка) отрабатывает в такой ситуации:
если у нас есть только один безусловный переход на метку, на которой стоит if (усл) goto
например:
goto 1;
---
---
1: if (усл) goto 2;
3:
оптимизируется в 
if (усл) goto 2;
goto 3;
----
----
3:

**Comment by d-enk** [comment]
Окей, спасибо

**Comment by Ex1sTs** [comment]
Да, можешь ты, можем мы, кто раньше, тот и успеет собственно )

**Comment by d-enk** [comment]
@Ex1sTs 

Что-то не то 
![image](https://user-images.githubusercontent.com/43112758/85222720-327a6500-b3c6-11ea-8ae4-f82da6ac9f00.png)

**Comment by Ex1sTs** [comment]
@d-enk это теперь тест, который не отработает, условия не совпадают. Там придется некоторые тесты переделывать теперь. Если можешь, пофикси сам, если нет, комментируй, мы сами поправим.

**Comment by d-enk** [comment]
а что здесь не совпадает
вроде как нужно просто добавить еще один кейс к тем 3
у которого как-то хитро будет чекаться, метка до ifgoto

**Comment by Ex1sTs** [comment]
по условию задачи не совпадает, там теперь на метке стоит не if а временная оператор #t1. Мы сделали задание по презентации, там такое не упоминается.

**Comment by d-enk** [comment]
кинул пулреквест
пару больших тестов пришлось закомменить

но чет мне подсказывает что лучше отказаться
от этого изменения все таки
слишком оно уж внизу лежит

**Comment by d-enk** [comment]
@Molkree @NikMozd @Ex1sTs 
так и че?
