### ISSUE TITLE
Удаление недостижимого кода

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#148]
На основе анализа графа потока управления удалять недостижимые базовые блоки.
Из первого, что приходит в голову: если у бблока нет родителей (кроме входного бблока), то удалять его. Далее удалять его потомков, однако следует не перестараться и не удалить достижимые блоки, так как из недостижимых вполне могут быть пути в достижимые.

**Comment by NikMozd** [comment]
Первое, что приходит в голову --- сделать обход графа (в глубину или ширину --- неважно) и найти блоки, в которые не пришли

**Comment by Molkree** [comment]
Но зачем делать обход, если граф уже и так хранит для каждого бблока его родителей и потомков?

**Comment by NikMozd** [comment]
Действительно, зачем делать обход графа, если для каждой вершины мы знаем смежные? 😂 
Вопрос очень странный, имхо. Плюс, вариант с обходом очевиднее и его проще реализовать

**Comment by Ex1sTs** [comment]
Для удаление недостижимого кода необходимо работать с CFG. Варианта 2
1) Реализуем оптимизацию графа через Exstantion и вызов внутри конструктора CFG(Ненужно будет изменять вызов CFG, но мы влезем в код команды Письменского, Лутченко).
2) Реализуем отдельный файлом Exstantion. Но тогда придется во всех местах где требуется получить граф, дописать вызов оптимизации графа.
Или ваши предложения

**Comment by Sirozu** [comment]
@NikMozd @Molkree 
Добавили удаление недостижимого кода.

Однако в ReachingDefinitionsBinaryTests и ReachingDefinitionsTests, пришлось закомментировать DisconnectedGraph(), возможно после удаления недостижимого кода теперь этот тест не имеет смысла.

Пришлось убрать свойство readonly с некоторых полей в cfg, а именно :
        private List<BasicBlock> _basicBlocks;
        private List<List<(int vertex, BasicBlock block)>> _children;
        private List<List<(int vertex, BasicBlock block)>> _parents;
        private Dictionary<BasicBlock, int> _blockToVertex;

Реализовано на моменте построения cfg, что бы автоматически убирался недостижимый код. 

Реализовали с помощью обхода графа в глубину, так как вариант с нахождением предков оказался неверным в случаях наличия бесконечных циклов в недостижимом коде.

**Comment by Molkree** [comment]
Было добавлено удаление недостижимого кода, однако оно применяется только при создании графа. По идее надо перестраивать граф после того, как глобальные оптимизации TAC вносят изменения в код. То есть что-то вроде такого:
```
if (answer.wasChanged)
{
    currentOpt = 0;
    var blocks = BasicBlockLeader.DivideLeaderToLeader(answer.instructions);
    var cfg = new ControlFlowGraph(blocks);
    result.Clear();
    for (var i = 1; i < cfg.GetCurrentBasicBlocks().Count - 1; ++i)
    {
        result.AddRange(cfg.GetCurrentBasicBlocks()[i].GetInstructions());
    }
}
```
После этого падают 11 тестов, их нужно исправить.

**Comment by Ex1sTs** [comment]
Разве у нас построение графа идет не после применения всех оптимизаций TAC ?

**Comment by Molkree** [comment]
Нет. Просто посмотрите на код здесь #109, недостижимый код тут не удалится.

**Comment by Ex1sTs** [comment]
я вытащил список ББл над которыми работает граф и он вот такой
![image](https://user-images.githubusercontent.com/33717301/85208872-57c29100-b33c-11ea-945d-2d041b284fae.png)

**Comment by Molkree** [comment]
Я понял тебя. Да, получается, что `ThreeAddressCodeOptimizer` нужно переделать немного больше. Предлагаю в него подавать не список инструкций, а граф (ну или просто перегрузку добавить). В любом случае внутри самого оптимизатора нужно будет перестраивать граф после каких-либо изменений от глобальных оптимизаций (code snippet в моём первом сообщении сегодня). @NikMozd, всё так?

**Comment by Ex1sTs** [comment]
@Molkree @NikMozd 
Итак, можно точнее сформулировать, что нужно сделать? У меня 2 варианта этой ситуации:
1) Если вы хотите с оптимизировать код на меньшее кол-во выполнения оптимизаций ( что бы локальные оптимизации не отрабатывали на недостижимом коде) 
тогда можно, вызывать построение CFG перед оптимизацией TAC (это удалить недостижимый код до оптимизаций ), вернуть список ББл из CFG и запихнуть его в оптимайзер, после оптимайзера, вызвать повторное построение CFG ( удалит код который стал недостижимым после оптимизаций).
2) Если просто не устраивает, что у нас в консоле "оптимизированные ББл" выводятся еще с недостижимым кодом ( т.к. он удаляется на этапе построения CFG, а это происходит после вывода), то давайте просто переместим вывод оптимизированных базовых блоков после построения CFG.

**Comment by NikMozd** [comment]
@Molkree имел в виду первый вариант. Я думаю, лучше спросить Михалковича о том, можно ли так сделать
