### ISSUE TITLE
Разработка простой IDE

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#149]
Как я себе это представляю:
- текстбокс для кода (аналог a.txt)
- чекбоксы для всех оптимизаций
- отдельный вывод после оптимизаций AST, после оптимизаций TAC
- как представлять граф красиво, я не знаю, @NikMozd предлагает GraphViz.

**Comment by Ukolnir** [comment]
Я возьму

**Comment by Ukolnir** [comment]
@Molkree может обойдемся без визуального представления графа?

**Comment by Molkree** [comment]
Обойдёмся

**Comment by Ukolnir** [comment]
@Molkree  @NikMozd 
Что входит в ide:
- представление кода в виде AST и TAC
- возможность потыкать в разные оптимизации по AST, TAC и итерационным алгоритмам
- выведение информации о ребрах графа (классификация), об обратных ребрах. о приводимости и естественных циклах
- возможность потыкать в итерационные алгоритмы

Не реализовано (потому что я хз как показать):
- дерево доминаторов
- различные обходы графа
- алгоритм упорядочивания графа
- построение областей

Не реализовано (потому что не реализовали/не слили команды):
- оптимизация по активным переменным
- оптимизация по глобальной def-use информации
- оптимизация по распространению констант (вообще была такая задача?)

**Comment by NikMozd** [comment]
Мои мысли по поводу того, что не знаешь, как делать:
1. Дерево можно выводить как список пар узел-родитель, используя нумерацию блоков
2. Обходы графа - как последовательности номеров
3. Алгоритм упорядочивания - так же
4. Про области хз, потому что я не знаю, что это такое 😅

**Comment by Ukolnir** [comment]
@NikMozd 
А надо ли вообще выводить пункты 1-3?

**Comment by Ukolnir** [comment]
В любом случае пункты 1-3 (вроде) выведены
