### ISSUE TITLE
Использование передаточной функции в достигающих определениях

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#41]
Попробовал использовать вашу ReachingTransferFunc для достигающих определений, вот [так](https://github.com/Taally/FIIT_6_compiler/commit/962c81d3ea78ebdc1cda296ab1523aa053dff8cc) это выглядит.
1. В нашем графе теперь есть фиктивный входной и выходной блоки, поэтому я их выкидываю из построения.
То есть в генерацию множеств gen/kill будет подаваться вот [такое](https://github.com/Taally/FIIT_6_compiler/commit/962c81d3ea78ebdc1cda296ab1523aa053dff8cc#diff-aee9a7e3c72b3a35c5a11330821718feR62) `g.GetCurrentBasicBlocks().Skip(1).Take(g.GetCurrentBasicBlocks().Count - 2).ToList()`, а не просто все блоки `g.GetCurrentBasicBlocks()`.
2. Я за присваивание считаю ещё и input.
3. У нас циклы for генерируются таким образом, что нужно ещё считать операцию PLUS, но только если это не временная переменная (чтобы учитывать инкремент счётчика цикла k = k + 1).
Пункты 2 и 3 меняют [условие](https://github.com/Taally/FIIT_6_compiler/commit/962c81d3ea78ebdc1cda296ab1523aa053dff8cc#diff-aee9a7e3c72b3a35c5a11330821718feR20) в GetDefs и GetGenKill с `if (instruction.Operation == "assign")` на `if (instruction.Operation == "assign" || instruction.Operation == "input" || instruction.Operation == "PLUS" && !instruction.Result.StartsWith("#"))`.

Если добавить такие изменения в ReachingTransferFunc, то все тесты [тут](https://github.com/Taally/FIIT_6_compiler/blob/master/SimpleLanguage.Tests/CFG/ReachingDefinitionsTests.cs) проходят. Если что-то не так, то буду рад услышать критику.

Нам нужно просто наше решение заменить на использование вашей функции? Или как-то оба варианта оставить? Не очень понял этот момент.
@VadimKaryakin @TheTapog

**Comment by VadimKaryakin** [comment]
Вроде всё так. Это задание само по себе не применяется, только в достигающих определениях. Это шло как часть достигающих определений и наверняка должно применяться у вас

**Comment by Molkree** [comment]
Хорошо, тогда и сливаю это.
