### ISSUE TITLE
Удаление мёртвого кода, используя InOut информацию из Достигающих определений (Володин, Моздоров)

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#43]
По идее нужно будет передавать что-то в алгоритм удаления мёртвого кода на основе DefUse-информации

**Comment by NikMozd** [comment]
Неактуально

**Comment by NikMozd** [comment]
Выяснилось, что это необходимо сделать

**Comment by NikMozd** [comment]
#252
