### ISSUE TITLE
Передаточная функция в структуре распространения констант (Лутченко, Письменский)

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#54]

**Comment by VadimKaryakin** [comment]
@d-enk передаточная функция вашей команды используется в итерационном алгоритме в структуре распространения констант, реализуемом моей командой. 
```
    public interface ITransFunc<T>
    {
        T Transfer(BasicBlock basicBlock, T input);
    }

```

**Comment by VadimKaryakin** [comment]
Это общий вид функции. 
Мой черновой вариант тут https://github.com/VadimKaryakin/FIIT_6_compiler/blob/master/DataFlowAnalysis/ConstPropagation.cs

**Comment by VadimKaryakin** [comment]
```

Dictionary<string, LatticeValue> Transfer(BasicBlock basicBlock, Dictionary<string, LatticeValue> input)

```
Например, так
