### ISSUE TITLE
Итерационный алгоритм в структуре распространения констант (Карякин, Карякин)

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#55]

**Comment by Molkree** [comment]
@TheTapog @VadimKaryakin, какие-нибудь сроки, когда вольёте это? Вы вроде бы уже показали, в чём заминка? Как я понимаю, #54 тоже вы вольёте?

**Comment by VadimKaryakin** [comment]
@Molkree Заминка в том, что Максиму нужно исправить #54 , чтобы тесты проходили. Он в курсе. После этого добавим.

**Comment by VadimKaryakin** [comment]
@Molkree Стоит отметить, что предоставленная мне реализация передаточной функции распространяет только целочисленные константы для определений с одним или двумя операндами (типо такого x = z, x = 5, x = u * z и пр. вариации)

**Comment by Molkree** [comment]
А чего бы ещё хотелось? Bool? Нужно ещё где-то помимо определений?

**Comment by VadimKaryakin** [comment]
Просто хз что Михалкович захочет как заказчик проверить, просто чтобы потом не допиливать на экзамене. Так-то "True" и "False" тоже константы. Максим от этого отказался, но правильно ли это

**Comment by Molkree** [comment]
Нет, я согласен, что логические константы это тоже константы, просто выясняю, что должно быть ещё по твоему мнению. (Других подходящих типов у нас вроде бы нет)

По поводу протяжки в определения с одним или двумя операндами: нужно ли ещё куда-то протягивать? Я сам не особо в курсе, поэтому и спрашиваю. Если протягивается между блоками в присваивания, то внутри блока локальная оптимизация протяжки констант по идее сделает всё остальное.

**Comment by Molkree** [comment]
Это задание включает в себя лишь реализацию итерационного алгоритма без проведения собственно оптимизации?

**Comment by VadimKaryakin** [comment]
-----------------
a=2              |
b=3              |
-----------------
          |
------------------
c = a + b + 2 |
------------------

Это два блока, информация из первого протянется во второй и, на мой взгляд, должна быть подстановка. Хотя в книге приводится определение лишь для бинарного оператора.

**Comment by VadimKaryakin** [comment]
Без проведения оптимизации, но в IN и OUT будут значения, которые соответствуют подстановке.

**Comment by VadimKaryakin** [comment]
![111143](https://user-images.githubusercontent.com/26149866/85184801-d4e8fa00-b299-11ea-8b8b-a3d53ef2198a.png)

**Comment by VadimKaryakin** [comment]
Например, такое вполне должно подставляться, на мой взгляд

**Comment by VadimKaryakin** [comment]
Локальная оптимизация протяжки констант вроде внутри блока распространяет и тут не поможет

**Comment by VadimKaryakin** [comment]
Я поправил, чтобы для всех выражений работало
