### ISSUE TITLE
Пропущенный(?) файл тестов

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#64]
@Tessecrack @aevseenko, что [это](https://github.com/Taally/FIIT_6_compiler/blob/master/SimpleLanguage.Tests/TACAlgebraicIdentitiesTests.cs) за файл такой? Он не участвует в тестах сейчас вообще. Это предполагаемая замена [текущему](https://github.com/Taally/FIIT_6_compiler/blob/master/SimpleLanguage.Tests/TAC/Simple/AlgebraicIdentitiesTest.cs) файлу с тестами?

**Comment by Tessecrack** [comment]
нет, это под нашу оптимизацию + (твоя из твоего теста)
так мы ему сдавали

вс, 24 мая 2020 г. в 19:08, Dmitry Volodin <notifications@github.com>:

**Comment by Tessecrack** [comment]
не замена короче

вс, 24 мая 2020 г. в 19:08, Dmitry Volodin <notifications@github.com>:

**Comment by Molkree** [comment]
Все эти тесты **не** проверяются сейчас. Их нужно добавить в проект. Вы этим будете сейчас заниматься? Если нет, то я добавлю.
И почему это не замена текущему файлу, если один единственный тест оттуда есть в этом файле?
P.S. Тесты на Доступные выражения тоже добавьте, пожалуйста.

**Comment by Tessecrack** [comment]
Добавь эти тесты в проект, если не сложно

*P.S. Добавим* *на доступные*



вс, 24 мая 2020 г. в 19:47, Dmitry Volodin <notifications@github.com>:
