### ISSUE TITLE
Построение областей (Карякин, Карякин)

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#73]

**Comment by NikMozd** [comment]
@VadimKaryakin , @TheTapog , естественные циклы уже сделали.

**Comment by Molkree** [comment]
Есть прогресс?

**Comment by VadimKaryakin** [comment]
Сегодня доделаю и добавлю

**Comment by VadimKaryakin** [comment]
#193 Доделал, завтра мб еще тестов добавлю. @Sirozu @Ex1sTs В процессе заметил, что NaturalLoop на a.txt находит циклы с 0 блоков. Мне это не мешает, если что

**Comment by Molkree** [comment]
> циклы с 0 блоков

как это?)

**Comment by VadimKaryakin** [comment]
Это проект двухдневной давности, где cfg от a.txt имеет 30-40 блоков.
![42424](https://user-images.githubusercontent.com/26149866/85293611-44cbd000-b4a6-11ea-9a60-2e829834967b.PNG)
И при выводе они просто отсеиваются
![313141](https://user-images.githubusercontent.com/26149866/85293711-64fb8f00-b4a6-11ea-98c6-45319d3f946d.PNG)

**Comment by VadimKaryakin** [comment]
@Molkree работает ли это так же сейчас сказать не могу, т.к. оптимизация трехадресного кода сокращает 106 инструкций к 8, как-то так

**Comment by Molkree** [comment]
Ну это правильно, что они отсеиваются, но всё же немного интересно, как возникают циклы из 0 блоков. Может быть это бблок с переходом на себя? Но почему не 1 тогда. @Sirozu @Ex1sTs, поясните?
