### ISSUE TITLE
Удаляются лишние метки

### ISSUE THREAD

**Issue by Molkree** [Taally/FIIT_6_compiler#86]
```
var a;
input(a);
1: if a == 0
    goto 3;
2: a = 2;
3: a = 3;
```

![image](https://user-images.githubusercontent.com/12860284/83976830-2fcb3a80-a905-11ea-8c2a-2c08f06451d2.png)

Метка 2 удаляется, хотя должна оставаться. Проявляется в комбинации `RemoveGotoThroughGoto` с `RemoveEmptyNodes`.

**Comment by Molkree** [comment]
После https://github.com/Taally/FIIT_6_compiler/commit/9bdf20ee6a93f9922913bd6e94e17fc473b1fec4 стало понятно, что удаляет `RemoveGotoThroughGoto`.  @TheTapog @VadimKaryakin

**Comment by TheTapog** [comment]
днём попробую что-нибудь с этим сделать

**Comment by TheTapog** [comment]
@Molkree Если временная метка у оператора, то удаляет как на слайде, иначе метка остаётся.
![презентация](https://user-images.githubusercontent.com/24213020/84494283-e175bd00-acb1-11ea-8dce-6807c422fa4a.PNG)
Для этого нужно одну строку поменять и тогда получится следующая последовательность оптимизаций:
трёхадресный код после базовых оптимизаций
![original](https://user-images.githubusercontent.com/24213020/84493471-77a8e380-acb0-11ea-9689-a25c0fce7332.png)
удаление пустых узлов
![empty1](https://user-images.githubusercontent.com/24213020/84493622-b8086180-acb0-11ea-8cae-60418caa1faf.png)
первое удаление переходов через переходы
![through1](https://user-images.githubusercontent.com/24213020/84493665-c9516e00-acb0-11ea-8ed0-3154053c73d6.png)
второе удаление переходов через переходы
![through2](https://user-images.githubusercontent.com/24213020/84493684-d2423f80-acb0-11ea-9098-87b31d940a7e.png)

строка 34 в файле ThreeAddressCodeRemoveGotoThroughGoto.cs
newInstructions.Add(new Instruction(com2.Label.StartsWith("L") && uint.TryParse(com2.Label.Substring(1), out _) ? "" : com2.Label, com2.Operation, com2.Argument1, com2.Argument2, com2.Result));

Наверное, будет не лишним это случай в тесты добавить?
